- import_tasks: ./distros/centos.yml
  when: ansible_distribution == 'CentOS'

- import_tasks: ./distros/lazy-mode.yml
  when: ansible_distribution != 'CentOS'

- name: Ensure Docker Config Directory Exist
  file: >
    path=/root/.docker
    recurse=yes
    state=directory

- name: Copy Docker Config Files
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: '{{ DOCKER_AUTH_FILE }}', dest: '/root/.docker/config.json' }
  when: DOCKER_AUTH_FILE is defined


- name: Render Docker Service Files
  template: src={{ item.src }} dest={{ item.dest }}
  notify: "restart docker"
  with_items:
    - src: 'docker-garbage-collector.service'
      dest: '/etc/systemd/system/'
    - src: 'docker-garbage-collector.timer'
      dest: '/etc/systemd/system/'
    - src: 'daemon.json'
      dest: '/etc/docker/'

- name: Enable Garbage Collector
  systemd:
      name: "{{ item }}"
      state: restarted
      daemon_reload: yes
      enabled: yes
  with_items:
    - "docker-garbage-collector"
    - "docker-garbage-collector.timer"
  when: DOCKER_ENABLE_PURGE == true